
    version: '3.7'

    services:
      app:
        build: .
        ports:
          - "5002:5002"
        depends_on:
          - redis
          - db
        environment:
          - NODE_ENV=production
          - PORT=5002
          - DB_HOST=db
          - DB_USER=postgres
          - DB_PASSWORD=postgres
          - DB_NAME=kenektshift
          - REDIS_HOST=redis
        volumes:
          - .:/app

      db:
        image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kenektshift
        volumes:
          - pgdata:/var/lib/postgresql/data

      redis:
        image: redis:alpine
        ports:
          - "6379:6379"

    volumes:
      pgdata:
    
    version: '3.7'

    services:
      prometheus:
        image: prom/prometheus
        volumes:
          - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090"

      grafana:
        image: grafana/grafana
        ports:
          - "3000:3000"
        volumes:
          - grafana-data:/var/lib/grafana
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      grafana-data:
    
    version: '3.7'

    services:
      db-master:
        image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kenektshift
        ports:
          - "5432:5432"
        volumes:
          - pgmasterdata:/var/lib/postgresql/data

      db-replica:
        image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kenektshift
          POSTGRES_PRIMARY_HOST: db-master
        ports:
          - "5433:5432"
        volumes:
          - pgreplicadata:/var/lib/postgresql/data

    volumes:
      pgmasterdata:
      pgreplicadata:
    
    version: '3.7'

    services:
      kong-db:
        image: postgres:13
        environment:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_PASSWORD: kong
        ports:
          - "5432:5432"
        volumes:
          - kong-db-data:/var/lib/postgresql/data

      kong:
        image: kong:latest
        environment:
          KONG_DATABASE: postgres
          KONG_PG_HOST: kong-db
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kong
          KONG_PROXY_ACCESS_LOG: /dev/stdout
          KONG_ADMIN_ACCESS_LOG: /dev/stdout
          KONG_PROXY_ERROR_LOG: /dev/stderr
          KONG_ADMIN_ERROR_LOG: /dev/stderr
          KONG_ADMIN_LISTEN: "0.0.0.0:8001"
        ports:
          - "8000:8000"
          - "8001:8001"
        depends_on:
          - kong-db
        volumes:
          - kong-data:/usr/local/kong

    volumes:
      kong-db-data:
      kong-data:
    