
    apiVersion: v1
    kind: Service
    metadata:
      name: kenektshift-service
    spec:
      type: LoadBalancer
      selector:
        app: kenektshift
      ports:
        - protocol: TCP
          port: 80
          targetPort: 5002
    