
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: user_service
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: user_service
          template:
            metadata:
              labels:
                app: user_service
            spec:
              containers:
              - name: user_service
                image: user_service:latest
                ports:
                - containerPort: 5001
                env:
                - name: NODE_ENV
                  value: "production"
                - name: DB_HOST
                  value: "db"
                - name: DB_USER
                  value: "postgres"
                - name: DB_PASSWORD
                  value: "postgres"
                - name: DB_NAME
                  value: "kenektshift_user_service"
                - name: REDIS_HOST
                  value: "redis"
        